name: Release

on:
  workflow_dispatch:
  push:
    tags:
      - "*"

jobs:
  build_artifacts:
    name: Build Artifacts
    runs-on: ubuntu-latest
    strategy:
      matrix:
        goos:
          - linux
          - windows
          - darwin
        goarch:
          - amd64
          - arm64
          - arm
    steps:
      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: "^1.21"
      - name: Check out code into the Go module directory
        uses: actions/checkout@v3
      - name: Build Client (${{ matrix.goos }}-${{ matrix.goarch }})
        env:
          GOOS: ${{ matrix.goos }}
          GOARCH: ${{ matrix.goarch }}
        run: go build -v -o ./bin/rclone-backup-${{ matrix.goos }}-${{ matrix.goarch }} ./cmd/backup/main.go
      - name: Rename Windows Binary
        if: ${{ matrix.goos == 'windows' }}
        env:
          FNAME: ./bin/rclone-backup-${{ matrix.goos }}-${{ matrix.goarch }}
        run: mv ${{ env.FNAME }} ${{ env.FNAME }}.exe
      - name: Upload Artifcats
        uses: actions/upload-artifact@v3
        with:
          name: artifacts
          path: ./bin/
          retention-days: 1

  deploy:
    name: Deploy to Releases
    runs-on: ubuntu-latest
    needs:
      - "build_artifacts"
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Retrieve backend binaries
        uses: actions/download-artifact@v3
        with:
          name: artifacts
          path: bin/
      - name: Publish GitHub release
        uses: softprops/action-gh-release@v2
        with:
          draft: true
          files: bin/*
